#switch between panes quickly using Alt+<arrow key> instead of ^B ^<arrow>
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

#set mouse scrolling and also clickable windows, panes, resizable panes (like GUI terminals - feels more natural for now)
set -g mouse on