#switch between panes quickly using Alt+<arrow key> instead of ^B ^<arrow>
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

#set mouse scrolling and also clickable windows, panes, resizable panes (like GUI terminals - feels more natural for now)
set -g mouse on

#enable more than default 20000 lines in tmux
set -g history-limit 50000

#enable vi mode for vim-like copy/paste key bindings
setw -g mode-keys vi

#TODO: check STYLE section of man tmux for visual customization options
